# -*- coding: utf-8 -*-
"""NSE Tickers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZAiS_0INYS8ay9rQrfdlUDbMB-wgJlTP
"""

import pandas as pd
import requests
from bs4 import BeautifulSoup
from google.colab import files

URL = 'https://indiancompanies.in/listed-companies-in-nse-with-symbol/'
page = requests.get(URL)
soup = BeautifulSoup(page.text, 'html.parser')
rows = soup.find_all('table')[0]

cname = []
cticker = []
for td in soup.find_all('table')[0].tbody.find_all('tr'):
        cname.append(td.find_all('td')[1].text.strip())
        cticker.append(td.find_all('td')[2].text.strip())

del cname[0]
del cticker[0]
df = pd.DataFrame(columns= ['Company_Name', 'Company_Ticker'])
df.Company_Name = cname
df.Company_Ticker = cticker
df.dropna(inplace= True)
df.to_csv('CompanySymbols.csv')
files.download('CompanySymbols.csv')